export const data = [
  {
    id: 1,
    date: "21/04/2023",
    branch: "Mumbai",
    type: "full",
    amount: "Rs 958280.95",
    bank: "DENA",
    requestedby: "Seth",
    status: "pending",
  },
  {
    id: 2,
    date: "17/02/2023",
    branch: "Mumbai",
    type: "full",
    amount: "Rs 545307.82",
    bank: "DENA",
    requestedby: "Jarad",
    status: "pending",
  },
  {
    id: 3,
    date: "04/12/2023",
    branch: "Andheri",
    type: "short",
    amount: "Rs 752962.26",
    bank: "YESBank",
    requestedby: "Tammy",
    status: "approved",
  },
  {
    id: 4,
    date: "13/08/2023",
    branch: "Kurla",
    type: "full",
    amount: "Rs 975235.40",
    bank: "DENA",
    requestedby: "Starr",
    status: "approved",
  },
  {
    id: 5,
    date: "20/12/2023",
    branch: "Mumbai",
    type: "short",
    amount: "Rs 661260.85",
    bank: "YESBank",
    requestedby: "Lexie",
    status: "pending",
  },
  {
    id: 6,
    date: "29/03/2023",
    branch: "Navi Mumbai",
    type: "short",
    amount: "Rs 678897.15",
    bank: "AXIS",
    requestedby: "Chery",
    status: "pending",
  },
  {
    id: 7,
    date: "22/06/2023",
    branch: "Mumbai",
    type: "short",
    amount: "Rs 701925.91",
    bank: "YESBank",
    requestedby: "Charlot",
    status: "approved",
  },
  {
    id: 8,
    date: "27/10/2023",
    branch: "Kurla",
    type: "full",
    amount: "Rs 422530.22",
    bank: "AXIS",
    requestedby: "Caryl",
    status: "approved",
  },
  {
    id: 9,
    date: "11/02/2023",
    branch: "Mumbai",
    type: "short",
    amount: "Rs 827706.32",
    bank: "AXIS",
    requestedby: "Thaddus",
    status: "pending",
  },
  {
    id: 10,
    date: "14/06/2023",
    branch: "Byculla",
    type: "full",
    amount: "Rs 271214.17",
    bank: "YESBank",
    requestedby: "Whitney",
    status: "pending",
  },
];
